### ISSUE TITLE
[Bug] Profile and Banner Image Adjustments not allowing image to resize

### ISSUE THREAD

**Issue by berot3** [SlRvb/Obsidian--ITS-Theme#123]
### Describe the bug
Can not change picture-size when there is the word "profile" in the image-text.

**Expected behavior**
It should be always possible to resize images.

### To Reproduce

try this:
`![Engelbart|10](https://history-computer.com/ModernComputer/Basis/images/Engelbart.jpg)`

and than add "profile" to the text:
`![Engel profile bart|10](https://history-computer.com/ModernComputer/Basis/images/Engelbart.jpg)`

As you can see it doesn't resize anymore.

Same for when "banner" appears somewhere in the text.

This comes from here: [Guide/Image-Positions.md](https://github.com/SlRvb/Obsidian--ITS-Theme/blob/144557b980e1594d207eca7e0a2c4a2e2dc32b44/Guide/Image-Positions.md)

But I don't think this is the wanted behavior?

### OS
Where does the bug occur?

- [x] Desktop
- [ ] Mobile

Obsidian Version: 0.15.8

**Comment by SlRvb** [comment]
Escaping the word `profile` should help.
`![Engel \profile bart|10](https://history-computer.com/ModernComputer/Basis/images/Engelbart.jpg)`

For external images I targeted the alias because it usually doesn't have text that appears and makes it a good place to allow for image adjustments. I'm not sure which course would be the best to fix this issue. Should I implement an `|unset` to undo any Image Adjustment stuff or should I have the option for a toggle/class to remove it from affecting images everywhere in my theme?
