### ISSUE TITLE
Callout Syntax & cssclass do not work

### ISSUE THREAD

**Issue by Missionary2112** [SlRvb/Obsidian--ITS-Theme#124]
### Describe the bug
Some Callout Syntax and cssclass in YAML do not work as it's supposed to.

**Expected behavior**
It should work accordingly.

### To Reproduce
1. Examine each case in Screenshots section below
2. See error

### Screenshots
1. **Some cssclass in YAML do not work**
- `tbl-b`: I do not see any border line in tables
- `bl-c`: Bullets still display multiple colors (neon light) in ascending level 
- `k-o`: kanban list has weird format rendering the content out of place
- `sphd-und-#`: Underline still display
- `h-line`: Header underlines still display
- `tag-notion`: Tag Pills
- `tag-outline`: does not work

2. **Timeline not aligned properly**
- Preview Mode
![2022-08-10_17 20 11_CSX](https://user-images.githubusercontent.com/98799613/184044773-f1b2f1c1-0ac8-47ff-bb63-32aa8aa5c4c1.jpg)
- Edit Mode
```
> [!timeline|t-l] **Title** *Subtitle*
> Left aligned timeline piece

> [!timeline|t-r t-2] **Title** *Subtitle*
> Right aligned timeline piece
```

3. **Aside Callout Title does not display**
- Preview Mode
![2022-08-10_17 29 06_CSX](https://user-images.githubusercontent.com/98799613/184045346-22bd4256-a754-4bb4-a84e-d6e39ccd2c6b.jpg)
- Edit Mode
```
>[!aside|title] Aside Title
>Aside Callout
```

4. **Callout dim is not dimmed**
- Edit Mode
```
>[!note|dim] dim
>Dim unless hovered
```

5. **Callout alt-l: The Title is not underlined**
- Preview Mode
![2022-08-10_17 57 25_CSX](https://user-images.githubusercontent.com/98799613/184047642-49d467cf-5946-49d0-83cb-2f4101018fd2.jpg)
- Edit Mode
```
>[!note|alt-line] alt-line
>No line separation
```
### OS
Where does the bug occur?

- [x] Desktop
- [ ] Mobile

Obsidian Version: v 0.15.9

**Comment by SlRvb** [comment]
- `tbl-b`: Seems to work for me 🤔 
![Obsidian_XVkoDYgNhA](https://user-images.githubusercontent.com/54087190/184255110-98dba09b-27e8-4a33-94ac-bdea7b37e396.png)

- `bl-c`: isn't meant to override Style Settings toggles for other bullet styles

- `k-o`: Also seems to work for me, it _needs_ to be combined with `kanban`
![Obsidian_eBMOcTHIvX](https://user-images.githubusercontent.com/54087190/184255446-a3eb6995-912c-4c15-94e3-7498324f2023.png)

- `sphd-und-#`: Also seems to work for me as well
![Obsidian_65t67NkUGJ](https://user-images.githubusercontent.com/54087190/184255702-49b78252-1b19-4348-99a8-04db07e80a19.png)

- `h-line`: Works as well
![ajo6taYqHY](https://user-images.githubusercontent.com/54087190/184255736-43e9b3cf-f79c-4842-80fd-9aefefd768ba.png)

- `tag-notion`: Does seem to work
- `tag-outline`: definitely does not work just because of Obsidian's css overriding it, so I'll fix that 🥴

**Comment by SlRvb** [comment]
- `Timeline` unfortunately is not easy to realign due to different note-width sizes and relative alignments not always working the way I want them to🥴 

- `Aside` Title should be `aside|show-title`

- `|dim` is meant to be used with `+` or `-` and only dims when collapsed 🙈
![Obsidian_5xVWGG5CaE](https://user-images.githubusercontent.com/54087190/184256579-f9f2b291-5b2c-407d-93e8-855446b6365b.png)

 - `alt-line`: seems to work for me 🤔
![Oa6sQypfgt](https://user-images.githubusercontent.com/54087190/184256684-a37edc0f-f1a9-48bd-8ac5-9ef8b6ce52e4.png)

**Comment by Missionary2112** [comment]
Yeah I believe Style Settings plugin overriding the functions I listed above. When I turned off Style Settings, they work exactly like your examples.

**Comment by Missionary2112** [comment]
Actually I meant with Style Settings plugin turned on, `timeline`, `aside`, `dim` still do work, but other `tbl-b`, `sphd-und-#`, `h-line`, `tag-notion` do not work. 

`k-o` with `kanban` work pretty weird but functional.
