### ISSUE TITLE
[Bug] Heading embedded text is all bold

### ISSUE THREAD

**Issue by Missionary2112** [SlRvb/Obsidian--ITS-Theme#278]
### Describe the bug
`## ![[file.name]]` will embed the file with all the texts are bolded. It's similar issue that I previously posted https://github.com/SlRvb/Obsidian--ITS-Theme/issues/118

**Expected behavior**
The text should not be bolded

### To Reproduce
1. Create embed in heading `## ![[file.name]]`
2. See error

### Screenshots
**Normal embed** 
![2024-02-01_18 18 22_CSX](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/98799613/8828cb86-f682-4fc1-a144-3592f676abfc)

**Embed in heading** `## ![[file.name]]`
![2024-02-01_18 18 55_CSX](https://github.com/SlRvb/Obsidian--ITS-Theme/assets/98799613/bd016f2e-58dd-45ca-acf8-e85430984a4e)

### OS
Where does the bug occur?

- [x] Desktop
- [ ] Mobile

### Versions
- Obsidian Version: v1.5.3
- ITS Theme Version: 1.2.33

**Comment by Missionary2112** [comment]
I put embeds in headings to quickly navigate events (from my journal) via outline.

**Comment by SlRvb** [comment]
Mmm gotcha, I'll see what I can do!

**Comment by SlRvb** [comment]
I think this should be fixed with ITS v1.2.39. Although, I _will_ say, this is default behavior even in the default theme due to css stuff, so this fix is mostly a bandaid solution that may not always work!

I might suggest you keep the heading dates and just embeds after so you can still maneuver around just as fast but with no font weight issues.

**Comment by Missionary2112** [comment]
Thank you for your fix and your suggestion 😀
