### ISSUE TITLE
[Bug] Admotion CSS supplied has strange behaviour

### ISSUE THREAD

**Issue by spiritualgeek** [SlRvb/Obsidian--ITS-Theme#85]
The CSS supplied at Guide/Alternate-Admonitions.md has some strange behaviour

1. It does not play nicely with live preview
![2022-03-13_17-36-27](https://user-images.githubusercontent.com/53917562/158067353-39ddc426-70a1-412f-aaa4-862aef9c537b.png)

2. In Reading view, text just spills over
![2022-03-13_17-38-20](https://user-images.githubusercontent.com/53917562/158067467-a52cee30-d8cf-4ff9-a11b-6bca63432f20.png)

Was hoping to use as a replacement to Admotion due to the issue with publishing

Thanks

**Comment by SlRvb** [comment]
I'll actually have to discontinue the admonitions snippet because actually Obsidian (and publish) now natively has support for [Callouts](https://help.obsidian.md/How+to/Use+callouts)!

It's a much better syntax than the way my admonitions work, so I'd say it'd be better to convert your admonitions to this format instead.

**Comment by spiritualgeek** [comment]
I saw that. Great timing! :) Thanks for responding.
